#!/usr/bin/env python3
"""
waf.py - Web Application Firewall (WAF) Detection
Primary:  wafw00f Python library  (pip install wafw00f)
Fallback: Manual fingerprinting via response headers + body + status codes
Detects: Cloudflare, Akamai, AWS WAF, Imperva, Sucuri, F5, Barracuda, and 100+ more
"""
import requests
import json
import sys
import subprocess
import shutil
from datetime import datetime
from colorama import Fore, Style, init
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
init(autoreset=True)

TIMEOUT = 15

# Manual fingerprint signatures for common WAFs
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "body": ["cloudflare", "cf-ray", "1020"],
        "cookies": ["__cfduid", "cf_clearance"]
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body": ["aws", "Request blocked"],
        "cookies": ["aws-waf-token"]
    },
    "Akamai": {
        "headers": ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed"],
        "body": ["AkamaiGHost", "Reference #"],
        "cookies": ["ak_bmsc", "bm_sz"]
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "body": ["incapsula", "Incapsula incident", "_Incapsula_Resource"],
        "cookies": ["incap_ses", "visid_incap"]
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["sucuri", "Access Denied - Sucuri Website Firewall"],
        "cookies": []
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-wa-info", "x-cnection"],
        "body": ["The requested URL was rejected", "BIG-IP"],
        "cookies": ["TS", "BIGipServer"]
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "body": ["barracudanetworks", "Barracuda Web Application Firewall"],
        "cookies": ["barra_counter_session"]
    },
    "ModSecurity": {
        "headers": ["mod_security", "x-mod-security"],
        "body": ["mod_security", "ModSecurity", "Not Acceptable!", "406 Not Acceptable"],
        "cookies": []
    },
    "Wordfence": {
        "headers": [],
        "body": ["generated by Wordfence", "Wordfence"],
        "cookies": ["wfvt_"]
    },
    "Fortinet FortiWeb": {
        "headers": ["x-requestid"],
        "body": ["FortiWeb", "Application Firewall"],
        "cookies": ["FORTIWAFSID"]
    },
    "DDoS-Guard": {
        "headers": ["ddos-guard"],
        "body": ["DDoS-Guard"],
        "cookies": ["__ddg1", "__ddg2"]
    },
    "Reblaze": {
        "headers": ["x-reblaze-protection"],
        "body": ["reblaze"],
        "cookies": ["rbzid"]
    },
    "Wallarm": {
        "headers": ["nginx-wallarm"],
        "body": ["Wallarm"],
        "cookies": []
    },
    "Nginx Rate Limit": {
        "headers": ["x-ratelimit"],
        "body": ["429 Too Many Requests"],
        "cookies": []
    }
}

# Payloads that trigger WAF blocks
WAF_TEST_PAYLOADS = [
    "/?id=1' OR '1'='1",           # SQLi
    "/?q=<script>alert(1)</script>",  # XSS
    "/?file=../../../../etc/passwd",   # LFI
    "/?cmd=;cat+/etc/passwd",         # RCE
]

def banner(title):
    print(f"\n{Fore.CYAN}{Style.BRIGHT}{'-'*12}[ {title} ]{'-'*12}{Style.RESET_ALL}")

def ok(msg):      print(f"{Fore.GREEN}[+]{Style.RESET_ALL} {msg}")
def warn(msg):    print(f"{Fore.YELLOW}[!]{Style.RESET_ALL} {msg}")
def err(msg):     print(f"{Fore.RED}[-]{Style.RESET_ALL} {msg}")
def info(msg):    print(f"{Fore.BLUE}[>]{Style.RESET_ALL} {msg}")
def finding(msg): print(f"{Fore.LIGHTWHITE_EX}> {msg}{Style.RESET_ALL}")


def detect_via_wafw00f(url):
    """Run wafw00f as subprocess (most accurate detection)."""
    result = {"method": "wafw00f", "detected": False, "waf_name": None, "raw_output": None}

    if not shutil.which("wafw00f"):
        warn("wafw00f binary not found — falling back to manual fingerprinting")
        warn("Install: pip install wafw00f")
        return None

    try:
        proc = subprocess.run(
            ["wafw00f", url, "-a", "-f", "json"],
            capture_output=True, text=True, timeout=60
        )
        output = proc.stdout.strip()
        result["raw_output"] = output

        # Parse JSON output
        try:
            data = json.loads(output)
            if isinstance(data, list) and data:
                waf_info = data[0]
                waf = waf_info.get("detected")
                if waf and waf != "None":
                    result["detected"] = True
                    result["waf_name"] = waf
                    ok(f"wafw00f detected: {Fore.RED}{waf}")
                else:
                    result["waf_name"] = None
                    ok("wafw00f: No WAF detected")
        except json.JSONDecodeError:
            # Try to parse plain text output
            for line in output.splitlines():
                if "is behind" in line.lower():
                    result["detected"] = True
                    parts = line.split("is behind")
                    if len(parts) > 1:
                        result["waf_name"] = parts[1].strip().strip(".")
                        ok(f"WAF detected: {result['waf_name']}")
                    break
                elif "no waf" in line.lower() or "not behind" in line.lower():
                    ok("wafw00f: No WAF detected")
                    break

        return result

    except subprocess.TimeoutExpired:
        warn("wafw00f timed out")
        return None
    except Exception as e:
        warn(f"wafw00f failed: {e}")
        return None


def fingerprint_waf_manual(domain):
    """Manual WAF fingerprinting by analyzing responses."""
    detected = []
    base_url = f"https://{domain}"

    info("Fetching baseline response...")
    baseline_headers = {}
    baseline_body = ""
    baseline_cookies = {}

    try:
        r = requests.get(base_url, timeout=TIMEOUT, verify=False,
                         headers={"User-Agent": "Mozilla/5.0"})
        baseline_headers = {k.lower(): v.lower() for k, v in r.headers.items()}
        baseline_body = r.text.lower()
        baseline_cookies = {k.lower(): str(v).lower() for k, v in r.cookies.items()}
    except Exception as e:
        warn(f"Baseline fetch failed: {e}")
        return detected

    # Check signatures
    for waf_name, sigs in WAF_SIGNATURES.items():
        score = 0
        matched = []

        for h in sigs["headers"]:
            if h.lower() in baseline_headers:
                score += 3
                matched.append(f"header:{h}")

        for b in sigs["body"]:
            if b.lower() in baseline_body:
                score += 2
                matched.append(f"body:{b}")

        for c in sigs["cookies"]:
            if any(c.lower() in ck for ck in baseline_cookies):
                score += 3
                matched.append(f"cookie:{c}")

        if score >= 2:
            detected.append({
                "waf": waf_name,
                "confidence": min(100, score * 10),
                "matched_indicators": matched
            })
            finding(f"{waf_name} detected (confidence: {min(100, score * 10)}%) via {matched}")

    return detected


def test_waf_blocking(domain):
    """Send attack payloads to see if WAF blocks them."""
    results = []
    base_url = f"https://{domain}"
    info("Sending attack payloads to test WAF blocking...")

    for payload in WAF_TEST_PAYLOADS:
        url = base_url + payload
        result = {"payload": payload, "blocked": False, "status_code": None, "evidence": None}
        try:
            r = requests.get(url, timeout=TIMEOUT, verify=False,
                             headers={"User-Agent": "Mozilla/5.0"})
            result["status_code"] = r.status_code
            if r.status_code in (403, 406, 429, 503):
                result["blocked"] = True
                result["evidence"] = f"HTTP {r.status_code}"
                ok(f"Payload blocked [{r.status_code}]: {payload[:50]}")
            else:
                warn(f"Payload NOT blocked [{r.status_code}]: {payload[:50]}")
        except Exception as e:
            result["error"] = str(e)
        results.append(result)

    blocked = sum(1 for r in results if r["blocked"])
    return {
        "total_payloads": len(results),
        "blocked": blocked,
        "not_blocked": len(results) - blocked,
        "details": results
    }


def process(domain):
    banner("WAF Detection")
    info(f"Target: {domain}")

    url = f"https://{domain}"
    output = {
        "domain": domain,
        "url": url,
        "waf_detected": False,
        "waf_name": None,
        "detection_method": None,
        "manual_fingerprints": [],
        "blocking_test": None,
        "confidence": None,
        "scanned_at": datetime.now().isoformat()
    }

    # 1. Try wafw00f first (most accurate)
    banner("wafw00f Detection")
    waf_result = detect_via_wafw00f(url)

    if waf_result and waf_result.get("detected"):
        output["waf_detected"] = True
        output["waf_name"] = waf_result["waf_name"]
        output["detection_method"] = "wafw00f"
        output["confidence"] = 95

    # 2. Manual fingerprinting (always run as supplement)
    banner("Manual Fingerprinting")
    manual = fingerprint_waf_manual(domain)
    output["manual_fingerprints"] = manual

    if not output["waf_detected"] and manual:
        best = max(manual, key=lambda x: x["confidence"])
        output["waf_detected"] = True
        output["waf_name"] = best["waf"]
        output["detection_method"] = "manual_fingerprint"
        output["confidence"] = best["confidence"]

    # 3. Test blocking behavior
    banner("Payload Blocking Test")
    output["blocking_test"] = test_waf_blocking(domain)

    # Final verdict
    banner("WAF Summary")
    if output["waf_detected"]:
        print(f"  {Fore.RED}{Style.BRIGHT}WAF DETECTED: {output['waf_name']}")
        print(f"  {Fore.WHITE}Method: {output['detection_method']}")
        print(f"  {Fore.WHITE}Confidence: {output['confidence']}%")
    else:
        print(f"  {Fore.GREEN}{Style.BRIGHT}No WAF detected")
        print(f"  {Fore.YELLOW}Site may be unprotected or WAF is in stealth mode")

    blocked = output["blocking_test"]["blocked"]
    total = output["blocking_test"]["total_payloads"]
    print(f"  {Fore.WHITE}Attack payloads blocked: {Fore.GREEN if blocked == total else Fore.RED}{blocked}/{total}")

    return output


if __name__ == "__main__":
    domain = sys.argv[1] if len(sys.argv) > 1 else input("Enter domain: ").strip()
    result = process(domain)
    print(json.dumps(result, indent=2, default=str))


